version: "3.8"

services:
  traefik-edu:
    container_name: portal-traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    image: traefik:latest
    networks:
      api_driven:
    restart: unless-stopped
    volumes:
      - portal_intranet:/acme
      - /run/user/1000/docker.sock:/var/run/docker.sock:ro

  php-traefik-edu:
    working_dir: /usr/share/nginx
    env_file:
      - .env
    container_name: php-i4f
    depends_on:
      - traefik-edu
    build:
      context: .
      dockerfile: ./php/Dockerfile
    networks:
      api_driven:
    restart: unless-stopped
    volumes:
      - ../docker.sites/api-portal:/usr/share/nginx/api-portal
      - ./php/config/conf.d/:/usr/local/etc/php/conf.d/
      - ./php/config/php.ini:/usr/local/etc/php/php.ini
      - ./php/xdebug.log:/var/xdebug.log
      - ./.bashrc:/root/.bashrc

  api-traefik-edu:
    working_dir: /usr/share/nginx/api-local
    env_file:
      - .env
    container_name: api-i4f
    depends_on:
      - php-traefik-edu
      - traefik-edu
    image: nginx:stable-alpine
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api-i4f`)
      - traefik.http.routers.api.entrypoints=web
    networks:
      api_driven:
    restart: unless-stopped
    volumes:
      - ../docker.sites/api-portal:/usr/share/nginx/api-portal
      - ./conf/nginx/conf.d/api-portal.conf:/etc/nginx/conf.d/api-portal.conf:ro
    command: [ nginx, '-g', 'daemon off;' ]

networks:
  api_driven:
    name: "api_driven"

volumes:
  portal_intranet: